from django.db import models

# Create your models here.

class champion(models.Model):
    name = models.CharField(max_length=255, blank=True, null=True)
    code = models.IntegerField(null=True, blank=True)
    armorperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    attackdamage = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    mpperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    attackspeedoffset = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    mp = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    armor = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    hp = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    hpregenperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    attackspeedperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    attackrange = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    movespeed = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    attackdamageperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    mpregenperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    critperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    spellblockperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    crit = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    mpregen = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    spellblock = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    hpregen = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    hpperlevel = models.DecimalField(null=True, blank=True, max_digits=8, decimal_places=5)
    def __unicode__(self):
        return str(self.name)


class item(models.Model):
    itemId = models.IntegerField(null=True, blank=True)
    tags = models.TextField(null=True, blank=True)
    plaintext = models.TextField(null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    name = models.CharField(null=True, blank=True, max_length=255)
    into = models.TextField(null=True, blank=True)
    total_cost = models.IntegerField(null=True, blank=True)
    purchasable = models.NullBooleanField(null=True, blank=True)
    sell_cost = models.IntegerField(null=True, blank=True)
    base_cost = models.IntegerField(null=True, blank=True)
    FlatArmorMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatAttackSpeedMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatBlockMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatCritChanceMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatCritDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatEXPBonus = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatHPPoolMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatHPRegenMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatMPPoolMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatMPRegenMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatMagicDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatMovementSpeedMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatPhysicalDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    FlatSpellBlockMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentArmorMo = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentAttackSpeedMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentBlockMo = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentCritChanceMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentCritDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentDodgeMo = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentEXPBonu = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentHPPoolMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentHPRegenMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentMPPoolMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentMPRegenMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentMagicDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentMovementSpeedMo = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentPhysicalDamageMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)
    PercentSpellBlockMod = models.DecimalField(null=True, blank=True, max_digits=10, decimal_places=5)

    def __unicode__(self):
        return str(self.name)