from django.db import models

# Create your models here.

class player(models.Model):
    player_id = models.IntegerField(null=True, blank=True)
    name = models.CharField(null=True, blank=True, max_length=255)
    profileIconId = models.IntegerField(null=True, blank=True)
    summonerLevel = models.IntegerField(null=True, blank=True)
    isHotStreak = models.NullBooleanField(null=True, blank=True)
    isFreshBlood = models.NullBooleanField(null=True, blank=True)
    leagueName = models.CharField(null=True, blank=True, max_length=255)
    isVeteran = models.NullBooleanField(null=True, blank=True)
    tier = models.CharField(null=True, blank=True, max_length=255)
    leaguePoints = models.IntegerField(null=True, blank=True)
    rank = models.CharField(null=True, blank=True, max_length=255)
    isInactive = models.NullBooleanField(null=True, blank=True)
    queueType = models.CharField(null=True, blank=True, max_length=255)
    wins = models.IntegerField(null=True, blank=True)
    def __unicode__(self):
        return str(self.player_id)


class matchInfo(models.Model):
    totalDamageDealtToChampions = models.IntegerField(null=True, blank=True)
    goldEarned = models.IntegerField(null=True, blank=True)
    item0 = models.IntegerField(null=True, blank=True)
    item1 = models.IntegerField(null=True, blank=True)
    item2 = models.IntegerField(null=True, blank=True)
    item3 = models.IntegerField(null=True, blank=True)
    item4 = models.IntegerField(null=True, blank=True)
    item5 = models.IntegerField(null=True, blank=True)
    item6 = models.IntegerField(null=True, blank=True)
    wardPlaced = models.IntegerField(null=True, blank=True)
    totalDamageTaken = models.IntegerField(null=True, blank=True)
    trueDamageDealtPlayer = models.IntegerField(null=True, blank=True)
    physicalDamageDealtPlayer = models.IntegerField(null=True, blank=True)
    trueDamageDealtToChampions = models.IntegerField(null=True, blank=True)
    visionWardsBought = models.IntegerField(null=True, blank=True)
    killingSprees = models.IntegerField(null=True, blank=True)
    totalUnitsHealed = models.IntegerField(null=True, blank=True)
    level = models.IntegerField(null=True, blank=True)
    neutralMinionsKilledYourJungle = models.IntegerField(null=True, blank=True)
    magicDamageDealtToChampions = models.IntegerField(null=True, blank=True)
    magicDamageDealtPlayer = models.IntegerField(null=True, blank=True)
    neutralMinionsKilledEnemyJungle = models.IntegerField(null=True, blank=True)
    assists = models.IntegerField(null=True, blank=True)
    magicDamageTaken = models.IntegerField(null=True, blank=True)
    numDeaths = models.IntegerField(null=True, blank=True)
    totalTimeCrowdControlDealt = models.IntegerField(null=True, blank=True)
    largestMultiKill = models.IntegerField(null=True, blank=True)
    physicalDamageTaken = models.IntegerField(null=True, blank=True)
    win = models.NullBooleanField(null=True, blank=True)
    team = models.IntegerField(null=True, blank=True)
    totalDamageDealt = models.IntegerField(null=True, blank=True)
    largestKillingSpree = models.IntegerField(null=True, blank=True)
    totalHeal = models.IntegerField(null=True, blank=True)
    minionsKilled = models.IntegerField(null=True, blank=True)
    timePlayed = models.IntegerField(null=True, blank=True)
    physicalDamageDealtToChampions = models.IntegerField(null=True, blank=True)
    championsKilled = models.IntegerField(null=True, blank=True)
    trueDamageTaken = models.IntegerField(null=True, blank=True)
    neutralMinionsKilled = models.IntegerField(null=True, blank=True)
    goldSpent = models.IntegerField(null=True, blank=True)
    gameId = models.IntegerField(null=True, blank=True)
    spell1 = models.IntegerField(null=True, blank=True)
    teamId  = models.IntegerField(null=True, blank=True)
    spell2 = models.IntegerField(null=True, blank=True)
    gameMode = models.CharField(blank=True, null=True, max_length=255)
    mapId = models.IntegerField(null=True, blank=True)
    level = models.IntegerField(null=True, blank=True)
    subType = models.CharField(blank=True, null=True, max_length=255)
    championId = models.IntegerField(null=True, blank=True)
    createDate = models.IntegerField(null=True, blank=True)